### ISSUE TITLE
URL scheme support for opening links.

### ISSUE THREAD

**Issue by timonus** [PumaBrowser/bugs-and-feature-requests#1]
Hello, I'm the developer of [Opener](https://opener.link), and I've gotten a few requests to add support for Puma. I need a URL scheme that can open links in order to do this.

I'm thinking something like

`http://apple.com` -> `pumabrowser-http://apple.com`
`https://google.com` -> `pumabrowser-https://google.com`

This would involve adding support for the `pumabrowser-http://` and `pumabrowser-https://` schemes to Puma and making invocations of them open the corresponding links in your browser.

**Comment by mjgardner** [comment]
> I've gotten a few requests to add support for Puma.

I just started using both Opener and Puma and confess I recently made such a request. 😊

**Comment by html5cat** [comment]
@timonus @mjgardner folks, biggest ooof for missing this somehow! 🤦🏻‍♂️
We'll add this in the next update. cc @nrudnyk

**Comment by nrudnyk** [comment]
@timonus @mjgardner it's now released in 3.8.2 with the following scheme: `pumabrowser://open-url?url=https://apple.com`
Please let us know if that worked!

**Comment by timonus** [comment]
Perfect, thanks!

**Comment by timonus** [comment]
https://mastodon.social/@Opener/111613541759118652
